"""
Systems and Software Engineering Life Cycle Processes

Value sets for the system life cycle processes defined by ISO/IEC/IEEE 15288.

Generated from: computing/systems_engineering.yaml
"""

from __future__ import annotations

from valuesets.generators.rich_enum import RichEnum

class SystemLifeCycleProcess15288(RichEnum):
    """
    The 30 system life cycle processes grouped by ISO/IEC/IEEE 15288:2015.
    """
    # Enum members
    ACQUISITION = "ACQUISITION"
    SUPPLY = "SUPPLY"
    LIFE_CYCLE_MODEL_MANAGEMENT = "LIFE_CYCLE_MODEL_MANAGEMENT"
    INFRASTRUCTURE_MANAGEMENT = "INFRASTRUCTURE_MANAGEMENT"
    PORTFOLIO_MANAGEMENT = "PORTFOLIO_MANAGEMENT"
    HUMAN_RESOURCE_MANAGEMENT = "HUMAN_RESOURCE_MANAGEMENT"
    QUALITY_MANAGEMENT = "QUALITY_MANAGEMENT"
    PROJECT_PLANNING = "PROJECT_PLANNING"
    PROJECT_ASSESSMENT_AND_CONTROL = "PROJECT_ASSESSMENT_AND_CONTROL"
    DECISION_MANAGEMENT = "DECISION_MANAGEMENT"
    RISK_MANAGEMENT = "RISK_MANAGEMENT"
    CONFIGURATION_MANAGEMENT = "CONFIGURATION_MANAGEMENT"
    INFORMATION_MANAGEMENT = "INFORMATION_MANAGEMENT"
    MEASUREMENT = "MEASUREMENT"
    QUALITY_ASSURANCE = "QUALITY_ASSURANCE"
    KNOWLEDGE_MANAGEMENT = "KNOWLEDGE_MANAGEMENT"
    BUSINESS_OR_MISSION_ANALYSIS = "BUSINESS_OR_MISSION_ANALYSIS"
    STAKEHOLDER_NEEDS_AND_REQUIREMENTS_DEFINITION = "STAKEHOLDER_NEEDS_AND_REQUIREMENTS_DEFINITION"
    SYSTEM_REQUIREMENTS_DEFINITION = "SYSTEM_REQUIREMENTS_DEFINITION"
    ARCHITECTURE_DEFINITION = "ARCHITECTURE_DEFINITION"
    DESIGN_DEFINITION = "DESIGN_DEFINITION"
    SYSTEM_ANALYSIS = "SYSTEM_ANALYSIS"
    IMPLEMENTATION = "IMPLEMENTATION"
    INTEGRATION = "INTEGRATION"
    VERIFICATION = "VERIFICATION"
    TRANSITION = "TRANSITION"
    VALIDATION = "VALIDATION"
    OPERATION = "OPERATION"
    MAINTENANCE = "MAINTENANCE"
    DISPOSAL = "DISPOSAL"

# Set metadata after class creation
SystemLifeCycleProcess15288._metadata = {
}

__all__ = [
    "SystemLifeCycleProcess15288",
]