"""
Fusion Energy Value Sets

Value sets for fusion energy concepts, confinement methods, and fuel types relevant to the DOE Accelerating Delivery of Fusion Energy challenge

Generated from: energy/nuclear/fusion.yaml
"""

from __future__ import annotations

from valuesets.generators.rich_enum import RichEnum

class FusionConfinementType(RichEnum):
    """
    Methods for confining plasma in fusion energy experiments and reactors
    """
    # Enum members
    MAGNETIC_CONFINEMENT_TOKAMAK = "MAGNETIC_CONFINEMENT_TOKAMAK"
    MAGNETIC_CONFINEMENT_STELLARATOR = "MAGNETIC_CONFINEMENT_STELLARATOR"
    INERTIAL_CONFINEMENT = "INERTIAL_CONFINEMENT"
    MAGNETO_INERTIAL = "MAGNETO_INERTIAL"
    LASER_DRIVEN = "LASER_DRIVEN"
    Z_PINCH = "Z_PINCH"
    FIELD_REVERSED_CONFIGURATION = "FIELD_REVERSED_CONFIGURATION"
    SPHEROMAK = "SPHEROMAK"

# Set metadata after class creation
FusionConfinementType._metadata = {
    "MAGNETIC_CONFINEMENT_TOKAMAK": {'description': 'Magnetic confinement using a toroidal chamber with an axial magnetic field and plasma current (tokamak)'},
    "MAGNETIC_CONFINEMENT_STELLARATOR": {'description': 'Magnetic confinement using external coils to generate a twisted toroidal magnetic field (stellarator)'},
    "INERTIAL_CONFINEMENT": {'description': 'Confinement by compressing fuel pellets to extreme densities using lasers or particle beams'},
    "MAGNETO_INERTIAL": {'description': 'Hybrid approach combining magnetic field compression with inertial confinement'},
    "LASER_DRIVEN": {'description': 'Fusion driven by high-power laser systems to compress and heat fuel targets'},
    "Z_PINCH": {'description': 'Confinement using the magnetic field generated by a large axial current through the plasma'},
    "FIELD_REVERSED_CONFIGURATION": {'description': 'Compact toroidal confinement where the magnetic field reverses direction inside the plasma'},
    "SPHEROMAK": {'description': 'Compact toroidal confinement with toroidal and poloidal magnetic fields of comparable strength'},
}

class FusionFuelType(RichEnum):
    """
    Types of nuclear fuel mixtures used in fusion reactions
    """
    # Enum members
    DEUTERIUM_TRITIUM = "DEUTERIUM_TRITIUM"
    DEUTERIUM_DEUTERIUM = "DEUTERIUM_DEUTERIUM"
    DEUTERIUM_HELIUM3 = "DEUTERIUM_HELIUM3"
    PROTON_BORON11 = "PROTON_BORON11"

# Set metadata after class creation
FusionFuelType._metadata = {
    "DEUTERIUM_TRITIUM": {'description': 'Deuterium-tritium (D-T) fuel, the most studied fusion fuel with the lowest ignition temperature', 'annotations': {'reactants': 'deuterium + tritium', 'products': 'helium-4 + neutron', 'energy_release': '17.6 MeV'}},
    "DEUTERIUM_DEUTERIUM": {'description': 'Deuterium-deuterium (D-D) fuel, avoiding the need for scarce tritium', 'annotations': {'reactants': 'deuterium + deuterium', 'products': 'helium-3 + neutron OR tritium + proton'}},
    "DEUTERIUM_HELIUM3": {'description': 'Deuterium-helium-3 (D-He3) fuel, producing fewer neutrons than D-T', 'annotations': {'reactants': 'deuterium + helium-3', 'products': 'helium-4 + proton', 'energy_release': '18.3 MeV'}},
    "PROTON_BORON11": {'description': 'Proton-boron-11 (p-B11) aneutronic fuel producing only charged particles', 'annotations': {'reactants': 'proton + boron-11', 'products': '3 helium-4', 'energy_release': '8.7 MeV'}},
}

class FusionPlasmaParameterType(RichEnum):
    """
    Key physical parameters measured and optimized in fusion plasma experiments
    """
    # Enum members
    PLASMA_TEMPERATURE = "PLASMA_TEMPERATURE"
    PLASMA_DENSITY = "PLASMA_DENSITY"
    CONFINEMENT_TIME = "CONFINEMENT_TIME"
    BETA_VALUE = "BETA_VALUE"
    ENERGY_GAIN_FACTOR_Q = "ENERGY_GAIN_FACTOR_Q"
    LAWSON_CRITERION = "LAWSON_CRITERION"
    PLASMA_CURRENT = "PLASMA_CURRENT"
    MAGNETIC_FIELD_STRENGTH = "MAGNETIC_FIELD_STRENGTH"

# Set metadata after class creation
FusionPlasmaParameterType._metadata = {
    "PLASMA_TEMPERATURE": {'description': 'Temperature of the plasma, typically measured in electron-volts (eV) or kelvin'},
    "PLASMA_DENSITY": {'description': 'Number density of particles in the plasma, measured in particles per cubic meter'},
    "CONFINEMENT_TIME": {'description': 'Average time a particle or unit of energy remains confined in the plasma'},
    "BETA_VALUE": {'description': 'Ratio of plasma kinetic pressure to magnetic pressure, a key performance metric'},
    "ENERGY_GAIN_FACTOR_Q": {'description': 'Ratio of fusion power output to external heating power input (Q factor)'},
    "LAWSON_CRITERION": {'description': 'Product of plasma density and confinement time required for net energy gain'},
    "PLASMA_CURRENT": {'description': 'Electric current flowing through the plasma, important for tokamak confinement'},
    "MAGNETIC_FIELD_STRENGTH": {'description': 'Strength of the magnetic field used to confine the plasma', 'meaning': 'NCIT:C156494'},
}

__all__ = [
    "FusionConfinementType",
    "FusionFuelType",
    "FusionPlasmaParameterType",
]